[book]
authors = ["Ankitects Pty Ltd und Mitwirkende"]
language = "de_DE"
multilingual = false
src = "src"
title = "Anki-Handbuch"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/RumovZ/anki-manual-de_DE"
cname = "docs.ankiweb.net"
additional-css = ["css/kbd.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
exclude = [ 'microsoft.com' ]

[output.html.fold]
enable = true
level = 0